allow-licenses:
  - 0BSD
  - 3D-Slicer-1.0
  - Abstyles
  - AdaCore-doc
  - Adobe-Display-PostScript
  - Adobe-Glyph
  - Adobe-Utopia
  - ADSL
  - Advanced-Cryptics-Dictionary
  - AFL-1.1
  - AFL-1.2
  - AFL-2.0
  - AFL-2.1
  - AFL-3.0
  - ALGLIB-Documentation
  - AMD-newlib
  - AMDPLPA
  - AML
  - AML-glslang
  - AMPAS
  - ANTLR-PD
  - ANTLR-PD-fallback
  - any-OSI
  - any-OSI-perl-modules
  - Apache-1.0
  - Apache-1.1
  - Apache-2.0
  - APAFML
  - App-s2p
  - Artistic-2.0
  - Aspell-RU
  - Baekmuk
  - Bahyph
  - Barr
  - bcrypt-Solar-Designer
  - Bitstream-Charter
  - Bitstream-Vera
  - BlueOak-1.0.0
  - Boehm-GC
  - Boehm-GC-without-fee
  - BOLA-1.1
  - Brian-Gladman-2-Clause
  - Brian-Gladman-3-Clause
  # - Brian-Gladman-3-Clause-no-conversion # excluded: not yet recognized by spdx-license-ids
  - BSD-1-Clause
  - BSD-2-Clause
  - BSD-2-Clause-first-lines
  - BSD-2-Clause-FreeBSD
  - BSD-2-Clause-NetBSD
  - BSD-2-Clause-Patent
  - BSD-2-Clause-pkgconf-disclaimer
  - BSD-2-Clause-Views
  - BSD-3-Clause
  - BSD-3-Clause-acpica
  - BSD-3-Clause-Attribution
  - BSD-3-Clause-Clear
  - BSD-3-Clause-flex
  - BSD-3-Clause-HP
  - BSD-3-Clause-LBNL
  - BSD-3-Clause-Modification
  - BSD-3-Clause-No-Nuclear-License-2014
  - BSD-3-Clause-No-Nuclear-Warranty
  - BSD-3-Clause-Open-MPI
  - BSD-3-Clause-Sun
  - BSD-3-Clause-Tso
  - BSD-4-Clause
  - BSD-4-Clause-Shortened
  - BSD-4-Clause-UC
  - BSD-4.3RENO
  - BSD-4.3TAHOE
  - BSD-Advertising-Acknowledgement
  - BSD-Attribution-HPND-disclaimer
  - BSD-Inferno-Nettverk
  - BSD-Mark-Modifications
  - BSD-Source-beginning-file
  - BSD-Source-Code
  - BSL-1.0
  - Buddy
  - bzip2-1.0.5
  - bzip2-1.0.6
  - Caldera
  - Caldera-no-preamble
  - CAPEC-tou
  - Catharon
  - CC-BY-1.0
  - CC-BY-2.0
  - CC-BY-2.5
  - CC-BY-2.5-AU
  - CC-BY-3.0
  - CC-BY-3.0-AT
  - CC-BY-3.0-AU
  - CC-BY-3.0-DE
  - CC-BY-3.0-IGO
  - CC-BY-3.0-NL
  - CC-BY-3.0-US
  - CC-BY-4.0
  - CC-BY-ND-1.0
  - CC-BY-ND-2.0
  - CC-BY-ND-2.5
  - CC-BY-ND-3.0
  - CC-BY-ND-3.0-DE
  - CC-BY-ND-4.0
  - CC-PDDC
  - CC-PDM-1.0
  - CC0-1.0
  - CDLA-Permissive-1.0
  - CDLA-Permissive-2.0
  - CERN-OHL-P-2.0
  - CFITSIO
  - checkmk
  - Clips
  - CMU-Mach
  - CMU-Mach-nodoc
  - CNRI-Jython
  - CNRI-Python
  - CNRI-Python-GPL-Compatible
  - COIL-1.0
  - Community-Spec-1.0
  - Cornell-Lossless-JPEG
  - Cronyx
  - CryptoSwift
  - Cube
  - curl
  - cve-tou
  - DEC-3-Clause
  - DL-DE-BY-2.0
  - DL-DE-ZERO-2.0
  - DocBook-DTD
  - DocBook-Schema
  - DocBook-Stylesheet
  - DocBook-XML
  - Dotseqn
  - DRL-1.0
  - DRL-1.1
  - DSDP
  - dtoa
  - dvipdfm
  - ECL-1.0
  - ECL-2.0
  - eGenix
  - Entessa
  - EPICS
  - ESA-PL-permissive-2.4
  - etalab-2.0
  - EUDatagrid
  - Eurosym
  - FBM
  - Ferguson-Twofish
  - FreeBSD-DOC
  - FSFAP-no-warranty-disclaimer
  - FSFULLRSD
  - FSFULLRWD
  - FTL
  - Furuseth
  - fwlw
  - Game-Programming-Gems
  - GD
  - generic-xts
  - Glulxe
  - Graphics-Gems
  - gtkbook
  - Gutmann
  - HaskellReport
  - HDF5
  - hdparm
  - HIDAPI
  - HP-1986
  - HP-1989
  - HPND-DEC
  - HPND-doc
  - HPND-doc-sell
  - HPND-export-US-acknowledgement
  - HPND-export-US-modify
  - HPND-export2-US
  - HPND-Fenneberg-Livingston
  - HPND-INRIA-IMAG
  - HPND-Intel
  - HPND-Kevlin-Henney
  - HPND-Markus-Kuhn
  - HPND-merchantability-variant
  - HPND-MIT-disclaimer
  - HPND-Netrek
  - HPND-Pbmplus
  - HPND-sell-MIT-disclaimer-xserver
  - HPND-sell-regexpr
  - HPND-sell-variant
  - HPND-sell-variant-critical-systems
  - HPND-sell-variant-MIT-disclaimer
  - HPND-sell-variant-MIT-disclaimer-rev
  - HPND-SMC
  - HPND-UC
  - HPND-UC-export-US
  - HTMLTIDY
  - hyphen-bulgarian
  - IBM-pibs
  - ICU
  - ImageMagick
  - iMatix
  - Imlib2
  - Info-ZIP
  - Inner-Net-2.0
  - InnoSetup
  - Intel
  - Intel-ACPI
  - ISC
  - ISC-Veillard
  - JasPer-2.0
  - jove
  - JPNIC
  - Kastrup
  - Knuth-CTAN
  - Libpng
  - libpng-1.6.35
  - libpng-2.0
  - libselinux-1.0
  - libtiff
  - libutil-David-Nugent
  - LiLiQ-P-1.1
  - Linux-man-pages-1-para
  - Linux-man-pages-copyleft
  - Linux-man-pages-copyleft-2-para
  - Linux-man-pages-copyleft-var
  - Linux-OpenIB
  - LOOP
  - LPD-document
  - LPPL-1.3c
  - lsof
  - Lucida-Bitmap-Fonts
  - LZMA-SDK-9.11-to-9.20
  - LZMA-SDK-9.22
  - Mackerras-3-Clause
  - Mackerras-3-Clause-acknowledgment
  - magaz
  - mailprio
  - MakeIndex
  - man2html
  - Martin-Birgmeier
  - metamail
  - Minpack
  - MIPS
  - MIT
  - MIT-0
  - MIT-advertising
  - MIT-Click
  - MIT-CMU
  - MIT-enna
  - MIT-feh
  - MIT-Festival
  - MIT-Khronos-old
  - MIT-Modern-Variant
  - MIT-open-group
  - MIT-STK
  - MIT-testregex
  - MIT-Wu
  - MITNFA
  - MMIXware
  - MPEG-SSG
  - mpi-permissive
  - MPL-2.0
  - mplus
  - MS-PL
  - MTLL
  - MulanPSL-1.0
  - MulanPSL-2.0
  - Multics
  - Mup
  - Naumen
  - NCBI-PD
  - NCL
  - NCSA
  - Net-SNMP
  - NetCDF
  - ngrep
  - NICTA-1.0
  - NIST-PD
  - NIST-PD-fallback
  - NIST-PD-TNT
  - NIST-Software
  - NLOD-1.0
  - NLOD-2.0
  - Noweb
  - NTIA-PD
  - NTP
  - Nunit
  - O-UDA-1.0
  - OAR
  - ODC-By-1.0
  - OGC-1.0
  - OGDL-Taiwan-1.0
  - OGL-Canada-2.0
  - OGL-UK-1.0
  - OGL-UK-2.0
  - OGL-UK-3.0
  - OLDAP-2.0
  - OLDAP-2.0.1
  - OLDAP-2.1
  - OLDAP-2.2
  - OLDAP-2.2.1
  - OLDAP-2.2.2
  - OLDAP-2.3
  - OLDAP-2.4
  - OLDAP-2.5
  - OLDAP-2.6
  - OLDAP-2.7
  - OLDAP-2.8
  - OML
  - OpenMDW-1.0
  - OpenSSL
  - OpenSSL-standalone
  - OpenVision
  - OPL-1.0
  - OPL-UK-3.0
  - OPUBL-1.0
  - OSC-1.0
  - OSSP
  - PADL
  - PDDL-1.0
  - PHP-3.0
  - PHP-3.01
  - Pixar
  - pkgconf
  - Plexus
  - pnmstitch
  - PostgreSQL
  - PSF-2.0
  - psfrag
  - Python-2.0
  - Python-2.0.1
  - radvd
  - Ruby
  - Ruby-pty
  - SAX-PD
  - SAX-PD-2.0
  - Saxpath
  - SCEA
  - SchemeReport
  - SGI-B-1.0
  - SGI-B-1.1
  - SGI-B-2.0
  - SGI-OpenGL
  - SGMLUG-PM
  - SGP4
  - SHL-0.5
  - SL
  - SMLNJ
  - SMPPL
  - SOFA
  - softSurfer
  - Soundex
  - Spencer-99
  - ssh-keyscan
  - SSH-OpenSSH
  - SSLeay-standalone
  - StandardML-NJ
  - Sun-PPP
  - Sun-PPP-2000
  - SunPro
  - SWL
  - swrule
  - Symlinks
  - TCL
  - TCP-wrappers
  - TekHVC
  - TermReadKey
  - ThirdEye
  - threeparttable
  - TPDL
  - TrustedQSL
  - TTWL
  - TTYP0
  - UCAR
  - ulem
  - UMich-Merit
  - Unicode-3.0
  - Unicode-DFS-2015
  - Unicode-DFS-2016
  - UnixCrypt
  - Unlicense
  - Unlicense-libtelnet
  - Unlicense-libwhirlpool
  - UPL-1.0
  - VSL-1.0
  - W3C
  - w3m
  - Widget-Workshop
  - WordNet
  - WTFNMFPL
  - wwl
  - X11
  - X11-distribute-modifications-variant
  - X11-no-permit-persons
  - X11-swapped
  - Xerox
  - Xfig
  - XFree86-1.1
  - xkeyboard-config-Zinoviev
  - xlock
  - Xnet
  - xpp
  - Zeeff
  - Zlib
  - zlib-acknowledgement
  - ZPL-2.0
  - ZPL-2.1
